/** Egypt destination cities for traveler listings */
export const EGYPT_ARRIVAL_CITIES = [
  "Alexandria",
  "Aswan",
  "Cairo",
  "Giza",
  "Hurghada",
  "Luxor",
  "Mansoura",
  "Port Said",
  "Sharm El Sheikh",
  "Suez",
  "Tanta",
] as const;

/** Common departure cities (searchable); travelers can still type custom cities elsewhere */
export const MAJOR_DEPARTURE_CITIES = [
  "Abu Dhabi",
  "Amman",
  "Amsterdam",
  "Athens",
  "Atlanta",
  "Baghdad",
  "Bangkok",
  "Barcelona",
  "Beijing",
  "Berlin",
  "Boston",
  "Brussels",
  "Bucharest",
  "Budapest",
  "Cairo",
  "Chicago",
  "Dallas",
  "Delhi",
  "Doha",
  "Dubai",
  "Dublin",
  "Frankfurt",
  "Geneva",
  "Hong Kong",
  "Houston",
  "Istanbul",
  "Jakarta",
  "Jeddah",
  "Johannesburg",
  "Kuala Lumpur",
  "Kuwait City",
  "Lagos",
  "Lisbon",
  "London",
  "Los Angeles",
  "Madrid",
  "Manila",
  "Marseille",
  "Melbourne",
  "Mexico City",
  "Miami",
  "Milan",
  "Montreal",
  "Moscow",
  "Mumbai",
  "Munich",
  "Muscat",
  "Nairobi",
  "New York",
  "Paris",
  "Prague",
  "Riyadh",
  "Rome",
  "San Francisco",
  "Seattle",
  "Seoul",
  "Shanghai",
  "Singapore",
  "Stockholm",
  "Sydney",
  "Tokyo",
  "Toronto",
  "Vienna",
  "Warsaw",
  "Washington",
  "Zurich",
] as const;

export const SORTED_EGYPT_CITIES = [...EGYPT_ARRIVAL_CITIES].sort((a, b) =>
  a.localeCompare(b)
);

export const SORTED_DEPARTURE_CITIES = [...MAJOR_DEPARTURE_CITIES].sort((a, b) =>
  a.localeCompare(b)
);
